# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-11-22 08:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socialapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='likes',
            new_name='image_likes',
        ),
    ]
